---
  # Parameters:
  #  mysql_root_password

  - name: Percona MySQL | Check if is installed
    command: test -x /usr/bin/mysql
    when: ansible_system == "Linux"
    register: mysql_present
    ignore_errors: yes
    tags:
      - mysql

  - name: Percona MySQL | Preset root password
    shell: echo mysql-server-5.6 mysql-server/{{item}} password {{mysql_root_password}} | debconf-set-selections
    when: ansible_os_family == "Debian" and mysql_present|failed
    with_items:
      - "root_password"
      - "root_password_again"
    become: yes
    tags:
      - mysql

  - name: Percona MySQL | Obtaining percona public key
    apt_key: keyserver=keyserver.ubuntu.com id=8507EFA5
    become: yes
    tags:
      - mysql

    #apt-key adv --keyserver keys.gnupg.net --recv-keys 8507EFA5 or
    #apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8507EFA5

#  - name: Obtaining percona public key
#    apt_key: url=https://www.percona.com/downloads/RPM-GPG-KEY-percona state=present
#    become: yes
#    tags:
#      - mysql

  - name: Percona MySQL | Add Debian apt repository
    apt_repository: repo="deb http://repo.percona.com/apt {{ansible_distribution_release}} main"
    when: ansible_os_family == "Debian" and mysql_present|failed
    become: yes
    tags:
      - mysql

  - name: Percona MySQL | Add Debian apt repository
    apt_repository: repo="deb-src http://repo.percona.com/apt {{ansible_distribution_release}} main"
    when: ansible_os_family == "Debian" and mysql_present|failed
    become: yes
    tags:
      - mysql

  - name: Percona MySQL | Apt-Pinning the packages
    template: src="{{role_dir}}/templates/00percona.pref.j2" dest="/etc/apt/preferences.d/00percona.pref"
    when: ansible_os_family == "Debian" and mysql_present|failed
    become: yes
    tags:
      - mysql


  - name: Percona MySQL | Install percona-server-server
    apt: update-cache=yes force=yes state=present pkg="percona-server-server"
    when: ansible_os_family == "Debian" and mysql_present|failed
    become: yes
    tags:
      - mysql

  - name: Percona MySQL | install libmysqlclient-dev
    apt: name=libmysqlclient-dev update_cache=yes state=latest
    when: ansible_os_family == "Debian" and mysql_present|failed
    become: yes
    tags:
      - mysql

  - name: Percona MySQL | Install Client
    apt: update-cache=yes force=yes state=present pkg="mysql-client"
    when: ansible_os_family == "Debian" and mysql_present|failed
    become: yes
    tags:
      - mysql

  - name: Percona MySQL | Restart
    service: name=mysql state=restarted
#    when: mysql_conf.changed
    when: docker_test is not defined
    become: yes
    tags:
      - mysql
